Acertando action

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -54,6 +54,7 @@ jobs:
           restore-keys: ${{ runner.os }}-m2
 
       - name: Test with Maven
+        run: mvn -B test
 
   sonarcloud-analysis:
     needs: test
@@ -71,7 +72,11 @@ jobs:
           distribution: 'temurin'
 
       - name: SonarCloud analysis
-        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ secrets.SONAR_PROJECTKEY }} -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }}
+        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
+          -Dsonar.projectKey=${{ secrets.SONAR_PROJECTKEY }} \
+          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
+          -Dsonar.host.url=https://sonarcloud.io \
+          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
 
       - name: Install xmllint
         run: sudo apt-get install -y libxml2-utils
@@ -79,58 +84,31 @@ jobs:
       - name: Check JaCoCo Coverage
         run: |
           JACOCO_XML_PATH=target/site/jacoco/jacoco.xml
+          if [ ! -f "$JACOCO_XML_PATH" ]; then
+            echo "JaCoCo report not found!"
+            exit 1
+          fi
+          
           COVERAGE=$(xmllint --xpath 'string(//report/counter[@type="INSTRUCTION"]/@covered)' $JACOCO_XML_PATH)
           MISSED=$(xmllint --xpath 'string(//report/counter[@type="INSTRUCTION"]/@missed)' $JACOCO_XML_PATH)
-          TOTAL=$(echo "$COVERAGE + $MISSED" | bc)
-          PERCENTAGE=$(echo "scale=2; $COVERAGE / $TOTAL * 100" | bc)
+          
+          TOTAL=$((COVERAGE + MISSED))
+          
+          if [ "$TOTAL" -eq 0 ]; then
+            echo "Error: Total instructions count is zero, cannot calculate coverage."
+            exit 1
+          fi
+
+          PERCENTAGE=$(echo "scale=2; $COVERAGE / $TOTAL * 70" | bc)
           echo "Code coverage percentage: $PERCENTAGE%"
+
           if (( $(echo "$PERCENTAGE < 50" | bc -l) )); then
             echo "Code coverage is below 50%: $PERCENTAGE%"
             exit 1
+          fi
 
   deploy-to-dockerhub:
     needs: sonarcloud-analysis
     runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_TOKEN }}
-
-      - name: Read current version
-        id: get_version
-        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
-
-      - name: Increment patch version
-        id: increment_version
-        run: |
-          VERSION=${{ env.VERSION }}
-          IFS='.' read -ra ADDR <<< "$VERSION"
-          PATCH=$((ADDR[2] + 1))
-          NEW_VERSION="${ADDR[0]}.${ADDR[1]}.$PATCH"
-          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
-          echo $NEW_VERSION > version.txt
-        shell: bash
-
-      - name: Debugging Information
-        run: |
-          git remote -v
-          git status
-
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v2
-        with:
-          context: .
-          file: ./Dockerfile
-          push: true
-          tags: |
-            wolwer/order:${{ env.NEW_VERSION }}
